# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70aaf43382f3e98f7c2227cadc97f063b864e49762436f1f068d8a512d28afb7b9a00fe9d5fb62a24e67a8779d87c56f642c0b03470e1b52382fffa849922ff5

test:
  secret_key_base: a577d11b1b6140461cc5be04ea5ce925d974a2c69e61f032689d0dd82dbcca9cce23aaec17faf4cc390d096e13b26227416d4d756de78e3d739bea3441b3bda9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
